services:
  - type: web
    name: outta-web-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
envVars:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    sync: false
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    sync: false

